import {readFileSync, writeFileSync} from 'node:fs';

function main() {
    const lua = readFileSync("C:/Program Files (x86)/Steam/steamapps/common/Factorio/data/base/prototypes/recipe.lua", {encoding: "ascii"});
    const recipes = parse(/data:extend\n\((.*)\)/s.exec(lua)[1]);
    writeFileSync("src/app/recipe.ts", generateCode(recipes));

    /*
    const cat = {};
    for (const r of recipes) {
        cat[r.category] = (cat[r.category] ?? []);
        cat[r.category].push(r.name);
    }
    console.log(cat);
    */
}

const prologue = `// this file was generated by import_recipe.mjs
import { ProducerType } from "./producer";
import { Cart, Res } from "./res";

export interface RecipeInfo {
	time: number;
	consumes?: Cart;
	produces?: number;
	allowProductivity?: boolean; 
}

export const recipes: {[P in ProducerType]: {[R in Res]?: RecipeInfo}} = `;

function generateCode(rawRecipes) {
    const producerFor = {
        undefined: "assembly",
        "oil-processing": "oilRefinery",
        "chemistry": "chemicalPlant",
        "crafting": "assembly",
        "advanced-crafting": "assembly",
        "crafting-with-fluid": "assembly",
        "smelting": "furnace",
        "rocket-building": "rocketSilo",
    }

    const ignoredRecipe = {
        // we don't yet support several recipes for the same product, so let's ignore the inferior ones
        "basic-oil-processing": true, // less efficient than advanced oil processing
        "coal-liquefaction": true, // probably less efficient than advanced oil processing
        "solid-fuel-from-petroleum-gas": true, // less efficient than advanced oil processing
        "solid-fuel-from-heavy-oil": true, // light oil is more efficient
        "light-oil-cracking": true, // less important than advanced oil processing

        // we don't yet support nuclear power (needs support for probabilistic outputs and selectable recipes for U-235)
        "uranium-processing": true,
        "kovarex-enrichment-process": true,
        "uranium-fuel-cell": true,
        "nuclear-fuel": true,
        "nuclear-fuel-reprocessing": true,
        "fission-reactor-equipment": true,
        "uranium-rounds-magazine": true,
        "atomic-bomb": true,
        "uranium-cannon-shell": true,
        "explosive-uranium-cannon-shell": true,
        "spidertron": true,
    }

    const res = {energy: 0, research: 0};
    const recipes = {
        energy: {
            energy: {
                time: 1,
            }
        },
        water: {
            water: {
                time: 1,
            },
            wood: { // I'm too lazy to register a dedicated producer for this, but we need a recipe because wood is consumed by other recipes
                time: 0,
            }
        },
        mine: {
            coal: {
                time: 1,
                produces: 1,
            },
            ironOre: {
                time: 1,
                produces: 1,
            },
            copperOre: {
                time: 1,
                produces: 1,
            },
            stone: {
                time: 1,
                produces: 1,
            },
        },
        pumpjack: {
            crudeOil: {
                time: 1,
                produces: 4, // minimum yield for average field would be 2
                consumes: {},
            }
        },
       	research: {
            research: {
                // will be overwritten by state
                time: 1,
            },
        },
    };
    const products = {};
    for (const r of rawRecipes) {
        if (ignoredRecipe[r.name]) {
            continue;
        }
        const producer = producerFor[r.category];
        if (!producer) {
            throw new Error("unknown category: " + r.category + " for recipe " + pretty(r));
        }
        const time = r.energy_required ?? 0.5; // some recipes don't specify energy_required, but all of them have 0.5 time according to the Wiki
        const allowProductivity = r.allow_productivity;
        const consumes = cartify(r.ingredients);
        
        let product;
        let produces;
        if (r.results.length == 1) {
            product = camelize(r.results[0].name);
            produces = r.results[0].amount;
        } else if (r.name == "advanced-oil-processing") {
            // for simplicity, allocate all pollution to petroleumGas
            product = "petroleumGas";
            produces = 55;

            // and give the heavy and light oil for free
            recipes[producer] = recipes[producer] ?? {};
            recipes[producer].heavyOil = recipes[producer].lightOil = {
                time: 0,
                produces: 1,
                allowProductivity,
            }
        } else {
            throw new Error("Several outputs: " + pretty(r));
        }

        if (products[product]) {
            throw new Error("Several recipes for " + product + ": " + products[product] + " and " + r.name);
        }
        products[product] = r.name;

        recipes[producer] = recipes[producer] ?? {};
        recipes[producer][product] = {time, consumes, produces, allowProductivity};

        res[product] = 0;
        for (const r in consumes) {
            res[r] = 0;
        }
    }

    const sortedRes = {};
    for (const r of Object.keys(res).toSorted()) {
        sortedRes[r] = 0;
    }
    //writeFileSync("src/app/res.new.json", JSON.stringify(sortedRes, undefined, "\t"));

    for (const p in recipes) {
        console.log(p, Object.keys(recipes[p]));
    }

    return prologue + JSON.stringify(recipes, undefined, "\t") + ";\n";
}


function cartify(ingredients) {
    const cart = {};
    for (const {type, name, amount} of ingredients) {
        if (type == "fluid" || type == "item") {
            cart[camelize(name)] = amount;
        } else {
            throw new Error("weird ingredient type:" + pretty(ingredients));
        }
    }
    return cart;
}

function camelize(name) {
    let r = "";
    let afterDash = false;
    for (const c of name) {
        if (c == "-") {
            afterDash = true;
        } else {
            r += afterDash ? c.toUpperCase() : c;
            afterDash = false;
        }
    }
    return r;
}

/**
 * @param {string} s the lua literal to parse
 */
function parse(s) {
    let i = 0;

    const reportError = (e) => {
        const start = s.lastIndexOf('\n', i) + 1;
        const end = s.indexOf('\n', i);
        const col = i - start;
        throw new Error(
            e + "\n"
            + s.substring(start, end) + "\n"
            + " ".repeat(col) + "^"
        );
    }

    const isAlpha = (c) => ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z');
    const isDigit = (c) => ('0' <= c && c <= '9');
    const isWhitespace = (c) => c == ' ' || c == '\n';

    const skipWhitespace = () => {
        for (;;) {
            while (isWhitespace(s[i])) i++;
            if (s.substring(i, i + 2) == "--") {
                i = s.indexOf("\n", i) + 1;
            } else {
                return;
            }
        }
    }

    const has = (x) => {
        skipWhitespace();
        if (s.substring(i, i + x.length) == x) {
            i += x.length;
            return true;
        } else {
            return false;
        }
    }

    const expect = (x) => {
        if (!has(x)) {
            reportError("expected " + x); 
        }
    }

    const readIdentifier = () => {
        if (isAlpha(s[i])) {
            const startIndex = i;
            while (isAlpha(s[i]) || s[i] == "_") i++;
            return s.substring(startIndex, i);
        } else {
            reportError("Identifier expected");
        }
    }

    const readString = () => {
        const start = i;
        const end = s.indexOf('"', i);
        if (end > 0) {
            i = end + 1;
            return s.substring(start, end);
        } else {
            reportError("Matching end quote not found");
        }
    }
    const readNumber = () => {
        const start = i;
        while (isDigit(s[i]) || s[i] == ".") i++;
        const n = parseFloat(s.substring(start, i));
        if (isNaN(n)) {
            reportError("invalid number format");
        } else {
            return n;
        }
    }

    const obj = () => {
        skipWhitespace();
        if (isAlpha(s[i])) {
            const o = {};
            let done;
            do {
                const key = readIdentifier();
                expect("=");
                const v = value();
                o[key] = v;
                const mayContinue = has(","); 
                done = has("}");
                if (!mayContinue && !done) {
                    reportError("expected , or }"); // in Lua, the trailing comma is optional ...
                }
            } while (!done);
            return o;
        } else {
            const a = [];
            let done;
            do {
                a.push(value());
                const mayContinue = has(",");
                done = has("}");
                if (!mayContinue && !done) {
                    reportError("expected , or }"); // in Lua, the trailing comma is optional ...
                }
            } while (!done);
            return a;
        }
    }

    const value = () => {
        if (has("{")) {
            return obj();
        }
        if (has('"')) {
            return readString();
        }
        if (isDigit(s[i])) {
            return readNumber();
        }
        if (has("true")) {
            return true;
        }
        if (has("false")) {
            return false;
        }
        reportError("unexpected value");
    }

    return value();
}

function pretty(o) {
    return JSON.stringify(o, undefined, 4);
}

main();