// this file was generated by import_recipe.mjs
import { ProducerType } from "./producer";
import { Cart, Res } from "./res";

export interface RecipeInfo {
	time: number;
	consumes?: Cart;
	produces?: number;
	allowProductivity?: boolean; 
}

export const recipes: {[P in ProducerType]: {[R in Res]?: RecipeInfo}} = {
	"energy": {
		"energy": {
			"time": 1
		}
	},
	"water": {
		"water": {
			"time": 1
		},
		"wood": {
			"time": 0
		}
	},
	"mine": {
		"coal": {
			"time": 1,
			"produces": 1
		},
		"ironOre": {
			"time": 1,
			"produces": 1
		},
		"copperOre": {
			"time": 1,
			"produces": 1
		},
		"stone": {
			"time": 1,
			"produces": 1
		}
	},
	"pumpjack": {
		"crudeOil": {
			"time": 1,
			"produces": 4,
			"consumes": {}
		}
	},
	"research": {
		"research": {
			"time": 1
		}
	},
	"assembly": {
		"speedModule": {
			"time": 15,
			"consumes": {
				"advancedCircuit": 5,
				"electronicCircuit": 5
			},
			"produces": 1
		},
		"speedModule2": {
			"time": 30,
			"consumes": {
				"speedModule": 4,
				"advancedCircuit": 5,
				"processingUnit": 5
			},
			"produces": 1
		},
		"speedModule3": {
			"time": 60,
			"consumes": {
				"speedModule2": 4,
				"advancedCircuit": 5,
				"processingUnit": 5
			},
			"produces": 1
		},
		"productivityModule": {
			"time": 15,
			"consumes": {
				"advancedCircuit": 5,
				"electronicCircuit": 5
			},
			"produces": 1
		},
		"productivityModule2": {
			"time": 30,
			"consumes": {
				"productivityModule": 4,
				"advancedCircuit": 5,
				"processingUnit": 5
			},
			"produces": 1
		},
		"productivityModule3": {
			"time": 60,
			"consumes": {
				"productivityModule2": 4,
				"advancedCircuit": 5,
				"processingUnit": 5
			},
			"produces": 1
		},
		"efficiencyModule": {
			"time": 15,
			"consumes": {
				"advancedCircuit": 5,
				"electronicCircuit": 5
			},
			"produces": 1
		},
		"efficiencyModule2": {
			"time": 30,
			"consumes": {
				"efficiencyModule": 4,
				"advancedCircuit": 5,
				"processingUnit": 5
			},
			"produces": 1
		},
		"efficiencyModule3": {
			"time": 60,
			"consumes": {
				"efficiencyModule2": 4,
				"advancedCircuit": 5,
				"processingUnit": 5
			},
			"produces": 1
		},
		"bulkInserter": {
			"time": 0.5,
			"consumes": {
				"ironGearWheel": 15,
				"electronicCircuit": 15,
				"advancedCircuit": 1,
				"fastInserter": 1
			},
			"produces": 1
		},
		"barrel": {
			"time": 1,
			"consumes": {
				"steelPlate": 1
			},
			"produces": 1,
			"allowProductivity": true
		},
		"nightVisionEquipment": {
			"time": 10,
			"consumes": {
				"advancedCircuit": 5,
				"steelPlate": 10
			},
			"produces": 1
		},
		"beltImmunityEquipment": {
			"time": 10,
			"consumes": {
				"advancedCircuit": 5,
				"steelPlate": 10
			},
			"produces": 1
		},
		"energyShieldEquipment": {
			"time": 10,
			"consumes": {
				"advancedCircuit": 5,
				"steelPlate": 10
			},
			"produces": 1
		},
		"energyShieldMk2Equipment": {
			"time": 10,
			"consumes": {
				"energyShieldEquipment": 10,
				"processingUnit": 5,
				"lowDensityStructure": 5
			},
			"produces": 1
		},
		"batteryEquipment": {
			"time": 10,
			"consumes": {
				"battery": 5,
				"steelPlate": 10
			},
			"produces": 1
		},
		"batteryMk2Equipment": {
			"time": 10,
			"consumes": {
				"batteryEquipment": 10,
				"processingUnit": 15,
				"lowDensityStructure": 5
			},
			"produces": 1
		},
		"solarPanelEquipment": {
			"time": 10,
			"consumes": {
				"solarPanel": 1,
				"advancedCircuit": 2,
				"steelPlate": 5
			},
			"produces": 1
		},
		"personalLaserDefenseEquipment": {
			"time": 10,
			"consumes": {
				"processingUnit": 20,
				"lowDensityStructure": 5,
				"laserTurret": 5
			},
			"produces": 1
		},
		"dischargeDefenseEquipment": {
			"time": 10,
			"consumes": {
				"processingUnit": 5,
				"steelPlate": 20,
				"laserTurret": 10
			},
			"produces": 1
		},
		"exoskeletonEquipment": {
			"time": 10,
			"consumes": {
				"processingUnit": 10,
				"electricEngineUnit": 30,
				"steelPlate": 20
			},
			"produces": 1
		},
		"personalRoboportEquipment": {
			"time": 10,
			"consumes": {
				"advancedCircuit": 10,
				"ironGearWheel": 40,
				"steelPlate": 20,
				"battery": 45
			},
			"produces": 1
		},
		"personalRoboportMk2Equipment": {
			"time": 20,
			"consumes": {
				"personalRoboportEquipment": 5,
				"processingUnit": 100,
				"lowDensityStructure": 20
			},
			"produces": 1
		},
		"laserTurret": {
			"time": 20,
			"consumes": {
				"steelPlate": 20,
				"electronicCircuit": 20,
				"battery": 12
			},
			"produces": 1
		},
		"flamethrowerTurret": {
			"time": 20,
			"consumes": {
				"steelPlate": 30,
				"ironGearWheel": 15,
				"pipe": 10,
				"engineUnit": 5
			},
			"produces": 1
		},
		"artilleryTurret": {
			"time": 40,
			"consumes": {
				"steelPlate": 60,
				"concrete": 60,
				"ironGearWheel": 40,
				"advancedCircuit": 20
			},
			"produces": 1
		},
		"gunTurret": {
			"time": 8,
			"consumes": {
				"ironGearWheel": 10,
				"copperPlate": 10,
				"ironPlate": 20
			},
			"produces": 1
		},
		"woodenChest": {
			"time": 0.5,
			"consumes": {
				"wood": 2
			},
			"produces": 1
		},
		"displayPanel": {
			"time": 0.5,
			"consumes": {
				"ironPlate": 1,
				"electronicCircuit": 1
			},
			"produces": 1
		},
		"ironStick": {
			"time": 0.5,
			"consumes": {
				"ironPlate": 1
			},
			"produces": 2,
			"allowProductivity": true
		},
		"stoneFurnace": {
			"time": 0.5,
			"consumes": {
				"stone": 5
			},
			"produces": 1
		},
		"boiler": {
			"time": 0.5,
			"consumes": {
				"stoneFurnace": 1,
				"pipe": 4
			},
			"produces": 1
		},
		"steamEngine": {
			"time": 0.5,
			"consumes": {
				"ironGearWheel": 8,
				"pipe": 5,
				"ironPlate": 10
			},
			"produces": 1
		},
		"ironGearWheel": {
			"time": 0.5,
			"consumes": {
				"ironPlate": 2
			},
			"produces": 1,
			"allowProductivity": true
		},
		"electronicCircuit": {
			"time": 0.5,
			"consumes": {
				"ironPlate": 1,
				"copperCable": 3
			},
			"produces": 1,
			"allowProductivity": true
		},
		"transportBelt": {
			"time": 0.5,
			"consumes": {
				"ironPlate": 1,
				"ironGearWheel": 1
			},
			"produces": 2
		},
		"electricMiningDrill": {
			"time": 2,
			"consumes": {
				"electronicCircuit": 3,
				"ironGearWheel": 5,
				"ironPlate": 10
			},
			"produces": 1
		},
		"burnerMiningDrill": {
			"time": 2,
			"consumes": {
				"ironGearWheel": 3,
				"stoneFurnace": 1,
				"ironPlate": 3
			},
			"produces": 1
		},
		"inserter": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 1,
				"ironGearWheel": 1,
				"ironPlate": 1
			},
			"produces": 1
		},
		"fastInserter": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 2,
				"ironPlate": 2,
				"inserter": 1
			},
			"produces": 1
		},
		"longHandedInserter": {
			"time": 0.5,
			"consumes": {
				"ironGearWheel": 1,
				"ironPlate": 1,
				"inserter": 1
			},
			"produces": 1
		},
		"burnerInserter": {
			"time": 0.5,
			"consumes": {
				"ironPlate": 1,
				"ironGearWheel": 1
			},
			"produces": 1
		},
		"pipe": {
			"time": 0.5,
			"consumes": {
				"ironPlate": 1
			},
			"produces": 1
		},
		"offshorePump": {
			"time": 0.5,
			"consumes": {
				"pipe": 3,
				"ironGearWheel": 2
			},
			"produces": 1
		},
		"copperCable": {
			"time": 0.5,
			"consumes": {
				"copperPlate": 1
			},
			"produces": 2,
			"allowProductivity": true
		},
		"smallElectricPole": {
			"time": 0.5,
			"consumes": {
				"wood": 1,
				"copperCable": 2
			},
			"produces": 2
		},
		"pistol": {
			"time": 5,
			"consumes": {
				"copperPlate": 5,
				"ironPlate": 5
			},
			"produces": 1
		},
		"submachineGun": {
			"time": 10,
			"consumes": {
				"ironGearWheel": 10,
				"copperPlate": 5,
				"ironPlate": 10
			},
			"produces": 1
		},
		"firearmMagazine": {
			"time": 1,
			"consumes": {
				"ironPlate": 4
			},
			"produces": 1
		},
		"lightArmor": {
			"time": 3,
			"consumes": {
				"ironPlate": 40
			},
			"produces": 1
		},
		"radar": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 5,
				"ironGearWheel": 5,
				"ironPlate": 10
			},
			"produces": 1
		},
		"smallLamp": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 1,
				"copperCable": 3,
				"ironPlate": 1
			},
			"produces": 1
		},
		"pipeToGround": {
			"time": 0.5,
			"consumes": {
				"pipe": 10,
				"ironPlate": 5
			},
			"produces": 2
		},
		"assemblingMachine1": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 3,
				"ironGearWheel": 5,
				"ironPlate": 9
			},
			"produces": 1
		},
		"repairPack": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 2,
				"ironGearWheel": 2
			},
			"produces": 1
		},
		"automationSciencePack": {
			"time": 5,
			"consumes": {
				"copperPlate": 1,
				"ironGearWheel": 1
			},
			"produces": 1,
			"allowProductivity": true
		},
		"logisticSciencePack": {
			"time": 6,
			"consumes": {
				"inserter": 1,
				"transportBelt": 1
			},
			"produces": 1,
			"allowProductivity": true
		},
		"lab": {
			"time": 2,
			"consumes": {
				"electronicCircuit": 10,
				"ironGearWheel": 10,
				"transportBelt": 4
			},
			"produces": 1
		},
		"stoneWall": {
			"time": 0.5,
			"consumes": {
				"stoneBrick": 5
			},
			"produces": 1
		},
		"assemblingMachine2": {
			"time": 0.5,
			"consumes": {
				"steelPlate": 2,
				"electronicCircuit": 3,
				"ironGearWheel": 5,
				"assemblingMachine1": 1
			},
			"produces": 1
		},
		"splitter": {
			"time": 1,
			"consumes": {
				"electronicCircuit": 5,
				"ironPlate": 5,
				"transportBelt": 4
			},
			"produces": 1
		},
		"undergroundBelt": {
			"time": 1,
			"consumes": {
				"ironPlate": 10,
				"transportBelt": 5
			},
			"produces": 2
		},
		"loader": {
			"time": 1,
			"consumes": {
				"inserter": 5,
				"electronicCircuit": 5,
				"ironGearWheel": 5,
				"ironPlate": 5,
				"transportBelt": 5
			},
			"produces": 1
		},
		"car": {
			"time": 2,
			"consumes": {
				"engineUnit": 8,
				"ironPlate": 20,
				"steelPlate": 5
			},
			"produces": 1
		},
		"engineUnit": {
			"time": 10,
			"consumes": {
				"steelPlate": 1,
				"ironGearWheel": 1,
				"pipe": 2
			},
			"produces": 1,
			"allowProductivity": true
		},
		"ironChest": {
			"time": 0.5,
			"consumes": {
				"ironPlate": 8
			},
			"produces": 1
		},
		"bigElectricPole": {
			"time": 0.5,
			"consumes": {
				"ironStick": 8,
				"steelPlate": 5,
				"copperCable": 4
			},
			"produces": 1
		},
		"mediumElectricPole": {
			"time": 0.5,
			"consumes": {
				"ironStick": 4,
				"steelPlate": 2,
				"copperCable": 2
			},
			"produces": 1
		},
		"shotgun": {
			"time": 10,
			"consumes": {
				"ironPlate": 15,
				"ironGearWheel": 5,
				"copperPlate": 10,
				"wood": 5
			},
			"produces": 1
		},
		"shotgunShell": {
			"time": 3,
			"consumes": {
				"copperPlate": 2,
				"ironPlate": 2
			},
			"produces": 1
		},
		"piercingRoundsMagazine": {
			"time": 6,
			"consumes": {
				"firearmMagazine": 2,
				"steelPlate": 1,
				"copperPlate": 2
			},
			"produces": 2
		},
		"grenade": {
			"time": 8,
			"consumes": {
				"ironPlate": 5,
				"coal": 10
			},
			"produces": 1
		},
		"steelFurnace": {
			"time": 3,
			"consumes": {
				"steelPlate": 6,
				"stoneBrick": 10
			},
			"produces": 1
		},
		"gate": {
			"time": 0.5,
			"consumes": {
				"stoneWall": 1,
				"steelPlate": 2,
				"electronicCircuit": 2
			},
			"produces": 1
		},
		"heavyArmor": {
			"time": 8,
			"consumes": {
				"copperPlate": 100,
				"steelPlate": 50
			},
			"produces": 1
		},
		"steelChest": {
			"time": 0.5,
			"consumes": {
				"steelPlate": 8
			},
			"produces": 1
		},
		"fastUndergroundBelt": {
			"time": 2,
			"consumes": {
				"ironGearWheel": 40,
				"undergroundBelt": 2
			},
			"produces": 2
		},
		"fastSplitter": {
			"time": 2,
			"consumes": {
				"splitter": 1,
				"ironGearWheel": 10,
				"electronicCircuit": 10
			},
			"produces": 1
		},
		"concrete": {
			"time": 10,
			"consumes": {
				"stoneBrick": 5,
				"ironOre": 1,
				"water": 100
			},
			"produces": 10
		},
		"hazardConcrete": {
			"time": 0.25,
			"consumes": {
				"concrete": 10
			},
			"produces": 10
		},
		"refinedConcrete": {
			"time": 15,
			"consumes": {
				"concrete": 20,
				"ironStick": 8,
				"steelPlate": 1,
				"water": 100
			},
			"produces": 10
		},
		"refinedHazardConcrete": {
			"time": 0.25,
			"consumes": {
				"refinedConcrete": 10
			},
			"produces": 10
		},
		"landfill": {
			"time": 0.5,
			"consumes": {
				"stone": 50
			},
			"produces": 1
		},
		"fastTransportBelt": {
			"time": 0.5,
			"consumes": {
				"ironGearWheel": 5,
				"transportBelt": 1
			},
			"produces": 1
		},
		"solarPanel": {
			"time": 10,
			"consumes": {
				"steelPlate": 5,
				"electronicCircuit": 15,
				"copperPlate": 5
			},
			"produces": 1
		},
		"rail": {
			"time": 0.5,
			"consumes": {
				"stone": 1,
				"ironStick": 1,
				"steelPlate": 1
			},
			"produces": 2
		},
		"locomotive": {
			"time": 4,
			"consumes": {
				"engineUnit": 20,
				"electronicCircuit": 10,
				"steelPlate": 30
			},
			"produces": 1
		},
		"cargoWagon": {
			"time": 1,
			"consumes": {
				"ironGearWheel": 10,
				"ironPlate": 20,
				"steelPlate": 20
			},
			"produces": 1
		},
		"railSignal": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 1,
				"ironPlate": 5
			},
			"produces": 1
		},
		"railChainSignal": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 1,
				"ironPlate": 5
			},
			"produces": 1
		},
		"trainStop": {
			"time": 0.5,
			"consumes": {
				"electronicCircuit": 5,
				"ironPlate": 6,
				"ironStick": 6,
				"steelPlate": 3
			},
			"produces": 1
		},
		"arithmeticCombinator": {
			"time": 0.5,
			"consumes": {
				"copperCable": 5,
				"electronicCircuit": 5
			},
			"produces": 1
		},
		"deciderCombinator": {
			"time": 0.5,
			"consumes": {
				"copperCable": 5,
				"electronicCircuit": 5
			},
			"produces": 1
		},
		"constantCombinator": {
			"time": 0.5,
			"consumes": {
				"copperCable": 5,
				"electronicCircuit": 2
			},
			"produces": 1
		},
		"selectorCombinator": {
			"time": 0.5,
			"consumes": {
				"advancedCircuit": 2,
				"deciderCombinator": 5
			},
			"produces": 1
		},
		"powerSwitch": {
			"time": 2,
			"consumes": {
				"ironPlate": 5,
				"copperCable": 5,
				"electronicCircuit": 2
			},
			"produces": 1
		},
		"programmableSpeaker": {
			"time": 2,
			"consumes": {
				"ironPlate": 3,
				"ironStick": 4,
				"copperCable": 5,
				"electronicCircuit": 4
			},
			"produces": 1
		},
		"poisonCapsule": {
			"time": 8,
			"consumes": {
				"steelPlate": 3,
				"electronicCircuit": 3,
				"coal": 10
			},
			"produces": 1
		},
		"slowdownCapsule": {
			"time": 8,
			"consumes": {
				"steelPlate": 2,
				"electronicCircuit": 2,
				"coal": 5
			},
			"produces": 1
		},
		"clusterGrenade": {
			"time": 8,
			"consumes": {
				"grenade": 7,
				"explosives": 5,
				"steelPlate": 5
			},
			"produces": 1
		},
		"defenderCapsule": {
			"time": 8,
			"consumes": {
				"piercingRoundsMagazine": 3,
				"electronicCircuit": 3,
				"ironGearWheel": 3
			},
			"produces": 1
		},
		"distractorCapsule": {
			"time": 15,
			"consumes": {
				"defenderCapsule": 4,
				"advancedCircuit": 3
			},
			"produces": 1
		},
		"destroyerCapsule": {
			"time": 15,
			"consumes": {
				"distractorCapsule": 4,
				"speedModule": 1
			},
			"produces": 1
		},
		"cliffExplosives": {
			"time": 8,
			"consumes": {
				"explosives": 10,
				"grenade": 1,
				"barrel": 1
			},
			"produces": 1
		},
		"rocket": {
			"time": 4,
			"consumes": {
				"explosives": 1,
				"ironPlate": 2
			},
			"produces": 1
		},
		"explosiveRocket": {
			"time": 8,
			"consumes": {
				"rocket": 1,
				"explosives": 2
			},
			"produces": 1
		},
		"piercingShotgunShell": {
			"time": 8,
			"consumes": {
				"shotgunShell": 2,
				"copperPlate": 5,
				"steelPlate": 2
			},
			"produces": 1
		},
		"cannonShell": {
			"time": 8,
			"consumes": {
				"steelPlate": 2,
				"plasticBar": 2,
				"explosives": 1
			},
			"produces": 1
		},
		"explosiveCannonShell": {
			"time": 8,
			"consumes": {
				"steelPlate": 2,
				"plasticBar": 2,
				"explosives": 2
			},
			"produces": 1
		},
		"artilleryShell": {
			"time": 15,
			"consumes": {
				"explosiveCannonShell": 4,
				"radar": 1,
				"explosives": 8
			},
			"produces": 1
		},
		"expressTransportBelt": {
			"time": 0.5,
			"consumes": {
				"ironGearWheel": 10,
				"fastTransportBelt": 1,
				"lubricant": 20
			},
			"produces": 1
		},
		"assemblingMachine3": {
			"time": 0.5,
			"consumes": {
				"speedModule": 4,
				"assemblingMachine2": 2
			},
			"produces": 1
		},
		"tank": {
			"time": 5,
			"consumes": {
				"engineUnit": 32,
				"steelPlate": 50,
				"ironGearWheel": 15,
				"advancedCircuit": 10
			},
			"produces": 1
		},
		"fluidWagon": {
			"time": 1.5,
			"consumes": {
				"ironGearWheel": 10,
				"steelPlate": 16,
				"pipe": 8,
				"storageTank": 1
			},
			"produces": 1
		},
		"artilleryWagon": {
			"time": 4,
			"consumes": {
				"engineUnit": 64,
				"ironGearWheel": 10,
				"steelPlate": 40,
				"pipe": 16,
				"advancedCircuit": 20
			},
			"produces": 1
		},
		"modularArmor": {
			"time": 15,
			"consumes": {
				"advancedCircuit": 30,
				"steelPlate": 50
			},
			"produces": 1
		},
		"powerArmor": {
			"time": 20,
			"consumes": {
				"processingUnit": 40,
				"electricEngineUnit": 20,
				"steelPlate": 40
			},
			"produces": 1
		},
		"powerArmorMk2": {
			"time": 25,
			"consumes": {
				"efficiencyModule2": 25,
				"speedModule2": 25,
				"processingUnit": 60,
				"electricEngineUnit": 40,
				"lowDensityStructure": 30
			},
			"produces": 1
		},
		"flamethrower": {
			"time": 10,
			"consumes": {
				"steelPlate": 5,
				"ironGearWheel": 10
			},
			"produces": 1
		},
		"landMine": {
			"time": 5,
			"consumes": {
				"steelPlate": 1,
				"explosives": 2
			},
			"produces": 4
		},
		"rocketLauncher": {
			"time": 10,
			"consumes": {
				"ironPlate": 5,
				"ironGearWheel": 5,
				"electronicCircuit": 5
			},
			"produces": 1
		},
		"combatShotgun": {
			"time": 10,
			"consumes": {
				"steelPlate": 15,
				"ironGearWheel": 5,
				"copperPlate": 10,
				"wood": 10
			},
			"produces": 1
		},
		"chemicalSciencePack": {
			"time": 24,
			"consumes": {
				"engineUnit": 2,
				"advancedCircuit": 3,
				"sulfur": 1
			},
			"produces": 2,
			"allowProductivity": true
		},
		"militarySciencePack": {
			"time": 10,
			"consumes": {
				"piercingRoundsMagazine": 1,
				"grenade": 1,
				"stoneWall": 2
			},
			"produces": 2,
			"allowProductivity": true
		},
		"productionSciencePack": {
			"time": 21,
			"consumes": {
				"electricFurnace": 1,
				"productivityModule": 1,
				"rail": 30
			},
			"produces": 3,
			"allowProductivity": true
		},
		"utilitySciencePack": {
			"time": 21,
			"consumes": {
				"lowDensityStructure": 3,
				"processingUnit": 2,
				"flyingRobotFrame": 1
			},
			"produces": 3,
			"allowProductivity": true
		},
		"expressUndergroundBelt": {
			"time": 2,
			"consumes": {
				"ironGearWheel": 80,
				"fastUndergroundBelt": 2,
				"lubricant": 40
			},
			"produces": 2
		},
		"fastLoader": {
			"time": 3,
			"consumes": {
				"fastTransportBelt": 5,
				"loader": 1
			},
			"produces": 1
		},
		"expressLoader": {
			"time": 10,
			"consumes": {
				"expressTransportBelt": 5,
				"fastLoader": 1
			},
			"produces": 1
		},
		"expressSplitter": {
			"time": 2,
			"consumes": {
				"fastSplitter": 1,
				"ironGearWheel": 10,
				"advancedCircuit": 10,
				"lubricant": 80
			},
			"produces": 1
		},
		"advancedCircuit": {
			"time": 6,
			"consumes": {
				"electronicCircuit": 2,
				"plasticBar": 2,
				"copperCable": 4
			},
			"produces": 1,
			"allowProductivity": true
		},
		"processingUnit": {
			"time": 10,
			"consumes": {
				"electronicCircuit": 20,
				"advancedCircuit": 2,
				"sulfuricAcid": 5
			},
			"produces": 1,
			"allowProductivity": true
		},
		"logisticRobot": {
			"time": 0.5,
			"consumes": {
				"flyingRobotFrame": 1,
				"advancedCircuit": 2
			},
			"produces": 1
		},
		"constructionRobot": {
			"time": 0.5,
			"consumes": {
				"flyingRobotFrame": 1,
				"electronicCircuit": 2
			},
			"produces": 1
		},
		"passiveProviderChest": {
			"time": 0.5,
			"consumes": {
				"steelChest": 1,
				"electronicCircuit": 3,
				"advancedCircuit": 1
			},
			"produces": 1
		},
		"activeProviderChest": {
			"time": 0.5,
			"consumes": {
				"steelChest": 1,
				"electronicCircuit": 3,
				"advancedCircuit": 1
			},
			"produces": 1
		},
		"storageChest": {
			"time": 0.5,
			"consumes": {
				"steelChest": 1,
				"electronicCircuit": 3,
				"advancedCircuit": 1
			},
			"produces": 1
		},
		"bufferChest": {
			"time": 0.5,
			"consumes": {
				"steelChest": 1,
				"electronicCircuit": 3,
				"advancedCircuit": 1
			},
			"produces": 1
		},
		"requesterChest": {
			"time": 0.5,
			"consumes": {
				"steelChest": 1,
				"electronicCircuit": 3,
				"advancedCircuit": 1
			},
			"produces": 1
		},
		"rocketSilo": {
			"time": 30,
			"consumes": {
				"steelPlate": 1000,
				"concrete": 1000,
				"pipe": 100,
				"processingUnit": 200,
				"electricEngineUnit": 200
			},
			"produces": 1
		},
		"cargoLandingPad": {
			"time": 30,
			"consumes": {
				"concrete": 200,
				"steelPlate": 25,
				"processingUnit": 10
			},
			"produces": 1
		},
		"roboport": {
			"time": 5,
			"consumes": {
				"steelPlate": 45,
				"ironGearWheel": 45,
				"advancedCircuit": 45
			},
			"produces": 1
		},
		"substation": {
			"time": 0.5,
			"consumes": {
				"steelPlate": 10,
				"advancedCircuit": 5,
				"copperCable": 6
			},
			"produces": 1
		},
		"accumulator": {
			"time": 10,
			"consumes": {
				"ironPlate": 2,
				"battery": 5
			},
			"produces": 1
		},
		"electricFurnace": {
			"time": 5,
			"consumes": {
				"steelPlate": 10,
				"advancedCircuit": 5,
				"stoneBrick": 10
			},
			"produces": 1
		},
		"beacon": {
			"time": 15,
			"consumes": {
				"electronicCircuit": 20,
				"advancedCircuit": 20,
				"steelPlate": 10,
				"copperCable": 10
			},
			"produces": 1
		},
		"pumpjack": {
			"time": 5,
			"consumes": {
				"steelPlate": 5,
				"ironGearWheel": 10,
				"electronicCircuit": 5,
				"pipe": 10
			},
			"produces": 1
		},
		"oilRefinery": {
			"time": 8,
			"consumes": {
				"steelPlate": 15,
				"ironGearWheel": 10,
				"stoneBrick": 10,
				"electronicCircuit": 10,
				"pipe": 10
			},
			"produces": 1
		},
		"electricEngineUnit": {
			"time": 10,
			"consumes": {
				"engineUnit": 1,
				"lubricant": 15,
				"electronicCircuit": 2
			},
			"produces": 1,
			"allowProductivity": true
		},
		"flyingRobotFrame": {
			"time": 20,
			"consumes": {
				"electricEngineUnit": 1,
				"battery": 2,
				"steelPlate": 1,
				"electronicCircuit": 3
			},
			"produces": 1,
			"allowProductivity": true
		},
		"storageTank": {
			"time": 3,
			"consumes": {
				"ironPlate": 20,
				"steelPlate": 5
			},
			"produces": 1
		},
		"pump": {
			"time": 2,
			"consumes": {
				"engineUnit": 1,
				"steelPlate": 1,
				"pipe": 1
			},
			"produces": 1
		},
		"chemicalPlant": {
			"time": 5,
			"consumes": {
				"steelPlate": 5,
				"ironGearWheel": 5,
				"electronicCircuit": 5,
				"pipe": 5
			},
			"produces": 1
		},
		"lowDensityStructure": {
			"time": 15,
			"consumes": {
				"steelPlate": 2,
				"copperPlate": 20,
				"plasticBar": 5
			},
			"produces": 1,
			"allowProductivity": true
		},
		"rocketFuel": {
			"time": 15,
			"consumes": {
				"solidFuel": 10,
				"lightOil": 10
			},
			"produces": 1,
			"allowProductivity": true
		},
		"satellite": {
			"time": 5,
			"consumes": {
				"lowDensityStructure": 100,
				"solarPanel": 100,
				"accumulator": 100,
				"radar": 5,
				"processingUnit": 100,
				"rocketFuel": 50
			},
			"produces": 1
		},
		"nuclearReactor": {
			"time": 8,
			"consumes": {
				"concrete": 500,
				"steelPlate": 500,
				"advancedCircuit": 500,
				"copperPlate": 500
			},
			"produces": 1
		},
		"centrifuge": {
			"time": 4,
			"consumes": {
				"concrete": 100,
				"steelPlate": 50,
				"advancedCircuit": 100,
				"ironGearWheel": 100
			},
			"produces": 1
		},
		"heatExchanger": {
			"time": 3,
			"consumes": {
				"steelPlate": 10,
				"copperPlate": 100,
				"pipe": 10
			},
			"produces": 1
		},
		"heatPipe": {
			"time": 1,
			"consumes": {
				"steelPlate": 10,
				"copperPlate": 20
			},
			"produces": 1
		},
		"steamTurbine": {
			"time": 3,
			"consumes": {
				"ironGearWheel": 50,
				"copperPlate": 50,
				"pipe": 20
			},
			"produces": 1
		}
	},
	"oilRefinery": {
		"lightOil": {
			"time": 0,
			"produces": 1,
			"allowProductivity": true
		},
		"heavyOil": {
			"time": 0,
			"produces": 1,
			"allowProductivity": true
		},
		"petroleumGas": {
			"time": 5,
			"consumes": {
				"water": 50,
				"crudeOil": 100
			},
			"produces": 55,
			"allowProductivity": true
		}
	},
	"chemicalPlant": {
		"lightOil": {
			"time": 2,
			"consumes": {
				"water": 30,
				"heavyOil": 40
			},
			"produces": 30,
			"allowProductivity": true
		},
		"sulfuricAcid": {
			"time": 1,
			"consumes": {
				"sulfur": 5,
				"ironPlate": 1,
				"water": 100
			},
			"produces": 50,
			"allowProductivity": true
		},
		"plasticBar": {
			"time": 1,
			"consumes": {
				"petroleumGas": 20,
				"coal": 1
			},
			"produces": 2,
			"allowProductivity": true
		},
		"solidFuel": {
			"time": 1,
			"consumes": {
				"lightOil": 10
			},
			"produces": 1,
			"allowProductivity": true
		},
		"sulfur": {
			"time": 1,
			"consumes": {
				"water": 30,
				"petroleumGas": 30
			},
			"produces": 2,
			"allowProductivity": true
		},
		"lubricant": {
			"time": 1,
			"consumes": {
				"heavyOil": 10
			},
			"produces": 10,
			"allowProductivity": true
		},
		"flamethrowerAmmo": {
			"time": 6,
			"consumes": {
				"steelPlate": 5,
				"crudeOil": 100
			},
			"produces": 1
		},
		"explosives": {
			"time": 4,
			"consumes": {
				"sulfur": 1,
				"coal": 1,
				"water": 10
			},
			"produces": 2,
			"allowProductivity": true
		},
		"battery": {
			"time": 4,
			"consumes": {
				"sulfuricAcid": 20,
				"ironPlate": 1,
				"copperPlate": 1
			},
			"produces": 1,
			"allowProductivity": true
		}
	},
	"furnace": {
		"copperPlate": {
			"time": 3.2,
			"consumes": {
				"copperOre": 1
			},
			"produces": 1,
			"allowProductivity": true
		},
		"ironPlate": {
			"time": 3.2,
			"consumes": {
				"ironOre": 1
			},
			"produces": 1,
			"allowProductivity": true
		},
		"stoneBrick": {
			"time": 3.2,
			"consumes": {
				"stone": 2
			},
			"produces": 1,
			"allowProductivity": true
		},
		"steelPlate": {
			"time": 16,
			"consumes": {
				"ironPlate": 5
			},
			"produces": 1,
			"allowProductivity": true
		}
	}
};
